---
image: debian:unstable

stages:
 - build_release

build:
 stage: build_release
 before_script:
   - apt update -qq
   - apt install -y -qq build-essential autoconf automake pkg-config libtool m4 autoconf-archive
   - apt install -y gcc-arm-linux-gnueabihf
 
 script:
   - "autoreconf -i"
   - "./configure --host=arm-linux-gnueabihf -prefix=${CSTOOL_DIR}/linux_arm_tool"
   - "make"

 artifacts:
  paths:
   - src/mbusd
   - doc/mbusd.8
 
